org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.3
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=mekanismavaritia
mod_name=Mekanism Avaritia
mod_license=MIT
mod_version=1.0
mod_group_id=io.github.masyumero
mod_authors=masyumero
mod_description=
mekanism_version=1.20.1-10.4.16.80
jei_version=15.20.0.105
